### ISSUE TITLE
"undefined: v8go.Context" in GitHub Actions

### ISSUE THREAD

**Issue by jimafisk** [rogchap/v8go#38]
First, thanks for sharing this project, it's [a lot faster](https://github.com/plentico/plenti/issues/3#issuecomment-656454543) than other things I've tried :rocket: 

It builds fine on my local (Ubuntu 18.04) laptop, but I'm having some trouble using it with GitHub Actions however (I'm using Goreleaser to automatically build binaries). Anywhere it's referenced I see errors like `undefined: v8go.Context` and `undefined: v8go.NewContext` (see: https://github.com/plentico/plenti/runs/930324024#step:8:151). 

GitHub Actions is using Ubuntu 18.04.4 too: https://github.com/plentico/plenti/runs/930279376#step:1:3

Is there something special I need to do to run this in CI environments? Thank you!

**Comment by jimafisk** [comment]
So it looks like my issue is not being able to build windows or mac, as already tracked here: https://github.com/rogchap/v8go/issues/7

The same thing happens locally if I try to build for these operating systems.

<details>
<summary>Error screenshot</summary>

![windows_mac_builds](https://user-images.githubusercontent.com/5913244/89207962-8f526900-d589-11ea-8171-91e93a14c437.png)


</details>

Since this is already being tracked, I'm closing this issue. Thanks!
